# Generated by Django 4.0.4 on 2022-06-04 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MenuHum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_hum',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
