# Generated by Django 3.2.13 on 2022-06-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MenuPet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_pet',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
